MyMvcApp/Models/BookModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MyMvcApp.Models
{
    public class BookModel
    {
        [Key]
        public string Id { get; set; }

        [Required(ErrorMessage = "Book Name Required")]
        public string BookName { get; set; }

        [Required(ErrorMessage = "Book Auther Required")]
        public string Author { get; set; }

        [Required(ErrorMessage = "Book Price Required")]
        public double Price { get; set; }
        
        [Required(ErrorMessage = "Book Date Required")]
        public DateTime Date { get; set; }
    }
}

MyMvcApp/Models/CustomerBookModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyMvcApp.Models
{
    public class CustomerBookModel
    {

        [Key]
        public string BorrowId { get; set; }

        public DateTime IssueDate { get; set; }

        public DateTime RecievedDate { get; set; }

        [ForeignKey("Book")]

        public string Id { get; set; }

        public BookModel Book { get; set; }

        [ForeignKey("Customer")]

        public string NIC { get; set; }

        public CustomerModel Customer { get; set; }

    }
}

MyMvcApp/Models/CustomerModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MyMvcApp.Models
{

    public class CustomerModel
    {
        [Key]
        [Required(ErrorMessage = "Nic Required")]
        public string NIC { get; set; }

        [Required(ErrorMessage = "Customer Name Required")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "Address Required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Contact No Required")]
        public string ContactNo { get; set; }
    }

}

MyMvcApp/Models/ErrorViewModel.cs
using System;

namespace MyMvcApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyMvcApp/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyMvcApp.Models;

namespace MyMvcApp.Controllers
{
    public class FormsController : Controller
    {
        private readonly ILogger<FormsController> _logger;
        private readonly IbookRepo _Ibook;

        public FormsController(IbookRepo Ibook, ILogger<FormsController> logger)
        {
            _Ibook = Ibook;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult AddBooks()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddBooks(BookModel book)
        {
            _logger.LogInformation("AddBooks action was invoked.");
            try
            {
                await _Ibook.AddBook(book);

                _logger.LogDebug("Executing AddBooks logic...");
                return RedirectToAction("AddBooks");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error adding book");
            }
            return View(book);

        }

        [HttpGet]
        public IActionResult AddCustomer()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddCustomer(CustomerModel customer)
        {
            _logger.LogInformation("AddCustomers action was invoked.");
            try
            {
                await _Ibook.AddCustomer(customer);

                _logger.LogDebug("Executing AddCustomers logic...");
                return RedirectToAction("AddCustomer");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error adding book");
            }
            return View(customer);
        }

        [HttpGet]
        public async Task<IActionResult> ShowBooks()
        {
            var books = await _Ibook.GetAllBooks();
            return View(books);
        }

        [HttpGet]

        public async Task<IActionResult> Delete(string Id)
        {
            var delete = await _Ibook.DeleteBook(Id);
            if (delete == false)
            {
                return NotFound();
            }

            return RedirectToAction("ShowBooks");
        }

        [HttpGet]
        public async Task<IActionResult> EditBooks(string Id)
        {
            var book = await _Ibook.GetBookById(Id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        [HttpPost]
        public async Task<IActionResult> EditBooks(BookModel edit)
        {
            var book = await _Ibook.EditBook(edit);

            if (book == false)
            {
                return NotFound();
            }
            else
            {
                return RedirectToAction("ShowBooks");
            }

        }



        [HttpGet]
        public async Task<IActionResult> ShowCustomers()
        {
            var customers = await _Ibook.GetAllCustomers();
            return View(customers);
        }


    }
}

MyMvcApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyMvcApp.Models;

namespace MyMvcApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

       
    }
}

MyMvcApp/Controllers/IssuesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using MyMvcApp.Models;

namespace MyMvcApp
{
    public class IssuesController : Controller
    {

        public ILogger<IssuesController> _logger;
        public IissueRepo _issueRepo;

        public IssuesController(ILogger<IssuesController> logger, IissueRepo iissueRepo)
        {
            this._logger = logger;
            this._issueRepo = iissueRepo;
        }

        [HttpGet]
        public async Task<IActionResult> BookIssue()
        {

            var books = await _issueRepo.GetAllBooks();
            ViewBag.BookList = new SelectList(books, "Id", "BookName");

            var Members = await _issueRepo.GetAllMembers();
            ViewBag.CustomerList = new SelectList(Members, "NIC", "CustomerName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BookIssue(CustomerBookModel Issue)
        {

            _logger.LogInformation("BookIssue action was invoked.");
            try
            {
                await _issueRepo.AddBookIssue(Issue);

                _logger.LogDebug("Executing BookIssue logic...");
                return RedirectToAction("BookIssue");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error Issue book");
            }
            return View(Issue);
        }
    }
}

MyMvcApp/Views/Forms/AddBooks.cshtml
@model MyMvcApp.Models.BookModel

<h2>Add Book</h2>

<a  asp-controller="Forms" asp-action="ShowBooks">Show Books</a>

<form asp-action="AddBooks" asp-controller="Forms" method="post">
    <div>
        <label>Book Id :</label>
        <input asp-for="Id" class="form-control" type="text" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div>
        <label>Book Name :</label>
        <input asp-for="BookName" class="form-control" type="text" />
        <span asp-validation-for="BookName" class="text-danger"></span>
    </div>

    <div>
        <label>Book Author :</label>
        <input asp-for="Author" class="form-control" type="text" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div>
        <label>Book Price :</label>
        <input asp-for="Price" class="form-control" type="number" step="0.01" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div>
        <label>Book Date :</label>
        <input asp-for="Date" class="form-control" type="date" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>

    <button type="submit">Submit</button>
</form>

MyMvcApp/Views/Forms/AddCustomer.cshtml
@model MyMvcApp.Models.CustomerModel

<h2>Add Customer</h2>
<a  asp-controller="Forms" asp-action="ShowCustomers">Show Customers</a>

<form asp-action="AddCustomer" asp-controller="Forms" method="post">
    <div>
        <label>Customer NIC :</label>
        <input asp-for="NIC" class="form-control" type="text" />
        <span asp-validation-for="NIC" class="text-danger"></span>
    </div>

    <div>
        <label>Customer Name :</label>
        <input asp-for="CustomerName" class="form-control" type="text" />
        <span asp-validation-for="CustomerName" class="text-danger"></span>
    </div>

    <div>
        <label>Customer Address :</label>
        <input asp-for="Address" class="form-control" type="text" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>

    <div>
        <label>Contact No :</label>
        <input asp-for="ContactNo" class="form-control" type="number" />
        <span asp-validation-for="ContactNo" class="text-danger"></span>
    </div>

    <button type="submit">Submit</button>
</form>

MyMvcApp/Views/Forms/EditBooks.cshtml
@model MyMvcApp.Models.BookModel

<h2>Edit Book</h2>

<form asp-controller="Forms" asp-action="EditBooks">
    <input type="hidden" asp-for="Id" />

    <div>
        <label>Book Name :</label>
        <input asp-for="BookName" class="form-control" type="text" />
        <span asp-validation-for="BookName" class="text-danger"></span>
    </div>

    <div>
        <label>Book Author :</label>
        <input asp-for="Author" class="form-control" type="text" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div>
        <label>Book Price :</label>
        <input asp-for="Price" class="form-control" type="number" step="0.01" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div>
        <label>Book Date :</label>
        <input asp-for="Date" class="form-control" type="date" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

MyMvcApp/Views/Forms/ShowBooks.cshtml
@model List<MyMvcApp.Models.BookModel>

<h2>Books</h2>

<table class="table">
    <thead>
        <tr>
            <td>Book Id</td>
            <td>Book Name</td>
            <td>Book Auther</td>
            <td>Book Price</td>
            <td>Book Date</td>
        </tr>
    <tbody>
            @foreach (var book in Model)
            {
            <tr>
                <td>@book.Id</td>
                <td>@book.BookName</td>
                <td>@book.Author</td>
                <td>@book.Price</td>
                <td>@book.Date</td>
                <td><a asp-controller="Forms" asp-action="Delete" asp-route-id="@book.Id" class="btn btn-primary"
                        onclick="return confirm('Are you sure you want delete this item?')">Delete Book</a>
                </td>
                <td>
                    <a asp-controller="Forms" asp-action="EditBooks" asp-route-id="@book.Id" class="btn btn-primary">Edit
                        Book</a>
                </td>
            </tr>
            }
    </tbody>
    </thead>
</table>

MyMvcApp/Views/Forms/ShowCustomers.cshtml
@model List<MyMvcApp.Models.CustomerModel>

<h2>Customers</h2>

<table class="table">
    <thead>
        <tr>
            <td>Customer NIC</td>
            <td>Customer Name</td>
            <td>Customer Address</td>
            <td>Contact NO</td>
            
        </tr>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>@customer.NIC</td>
                    <td>@customer.CustomerName</td>
                    <td>@customer.Address</td>
                    <td>@customer.ContactNo</td>
                    
                </tr>
            }
        </tbody>
    </thead>
</table>

MyMvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyMvcApp/Views/Issues/BookIssue.cshtml
@model MyMvcApp.Models.CustomerBookModel

<h2>Issue Book</h2>

<form asp-action="BookIssue" asp-controller="Issues" method="post">
    
    <div>
        <label>Book Name:</label>
        <select asp-for="Id" asp-items="ViewBag.BookList" class="form-control">
            <option value="">-- Select Book --</option> 
        </select>
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    
    <div>
        <label>Member Name :</label>
        <select asp-for="NIC" asp-items="ViewBag.CustomerList" class="form-control">
            <option value="">-- Select Book --</option> 
        </select>
        <span asp-validation-for="NIC" class="text-danger"></span>
    </div>

    <div>
        <label>Issue Date :</label>
        <input asp-for="IssueDate" class="form-control" type="date" />
        <span asp-validation-for="IssueDate" class="text-danger"></span>
    </div>

    <div>
        <label>Receving Date :</label>
        <input asp-for="RecievedDate" class="form-control" type="date" />
        <span asp-validation-for="RecievedDate" class="text-danger"></span>
    </div>

    <button type="submit">Submit</button>
</form>

MyMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyMvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyMvcApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="AddCustomer">Add Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="AddBooks">Add Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Issues" asp-action="BookIssue">Issue Book</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyMvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>